### PR TITLE
[WIP] Scrub out NanoVG, OpenGL, and GLFW.

### PR DESCRIPTION
**Pull request by crertel**
Exactly what it says on the tin. Still in progress.

Open questions:

* Should we bring back context as a placeholder to demonstrate to folks how to pass that around if they port to new backends?
* I do some varargs hackery in a `#define` so I can log. We'll need to snarf up stdout in Elixir, probably. What say we?
* I left in a lot of the image and font stuff where possible to keep that feel--it's probably not needed. Should they go?
* Is it okay I stripped out a lot of deadcode?
* Do we want to allow for some way of injecting input events back?
* Any other ideas?

### CODE REVIEW

**Comment by ringlej** [comment]
Hi @crertel. This is great!
I had already started down a very similar path myself. Please allow me to post my own PR with my WIP before you do anything more with this PR. My WIP will have a lot of conflicts against this PR, so it makes sense to me to put it up as a "competing" PR for us to compare side by side. I'll have mine up by Monday night at the latest.

Thanks!

**Comment by ringlej** [comment]
My laptop died (won't power on) and I'm getting a replacement sent to me overnight. So I won't have my PR up tonight. Look for it tomorrow

**Comment by ringlej** [comment]
Please see https://github.com/ScenicFramework/scenic_driver_local/pull/26
After working through the arduous task of separating the scenic logic from the rendering logic, I decided that it was best to propose a PR directly to the scenic_driver_local repo instead. I think there are long term benefits of adopting my PR there instead of forking separate drivers

**Comment by crertel** [comment]
Closing this for now, since I think the work @ringlej has done makes this obsolete. :)

**Pull request closed without merging**
